services:
    _defaults:
        public: true

    hraph_sylius_paygreen_plugin.event_listener.paygreen_shop_notifier:
        class: Hraph\SyliusPaygreenPlugin\EventListener\PaygreenShopNotifier
        arguments:
            - "@hraph_sylius_paygreen_plugin.client.repository.paygreen_shop_repository"
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postUpdate'
                entity: 'Hraph\SyliusPaygreenPlugin\Entity\PaygreenShop'
            -   name: 'doctrine.orm.entity_listener'
                event: 'prePersist'
                entity: 'Hraph\SyliusPaygreenPlugin\Entity\PaygreenShop'
