services:
    hraph_sylius_paygreen_plugin.form.type.paygreen_configuration:
        class: Hraph\SyliusPaygreenPlugin\Form\Type\PaygreenConfigurationType
        arguments:
            - "%hraph_sylius_paygreen_plugin.client.force_use_authorize%" # Parameter fitted in with force_use_authorize dynamically on load
        tags:
            - { name: sylius.gateway_configuration_type, type: paygreen, label: hraph_sylius_paygreen_plugin.ui.paygreen_gateway_label } # Define name and label for admin configuration
            - { name: form.type }
    hraph_sylius_paygreen_plugin.form.type.paygreen_multiple_configuration:
        class: Hraph\SyliusPaygreenPlugin\Form\Type\PaygreenMultipleConfigurationType
        arguments:
            - "%hraph_sylius_paygreen_plugin.client.force_use_authorize%" # Parameter fitted in with force_use_authorize dynamically on load
        tags:
            - { name: sylius.gateway_configuration_type, type: paygreen_multiple, label: hraph_sylius_paygreen_plugin.ui.paygreen_multiple_gateway_label } # Define name and label for admin configuration
            - { name: form.type }
