services:
    hraph_sylius_paygreen_plugin.form.type.paygreen_configuration:
        class: Hraph\SyliusPaygreenPlugin\Form\Type\PaygreenConfigurationType
        tags:
            - { name: sylius.gateway_configuration_type, type: paygreen, label: hraph_sylius_paygreen_plugin.ui.paygreen_gateway_label } # Define name and label for admin configuration
            - { name: form.type }
