services:
    hraph_sylius_paygreen_plugin.state_machine.admin_order_payment_state_resolver:
        class: Hraph\SyliusPaygreenPlugin\StateMachine\AdminOrderPaymentStateResolver
        public: true
        arguments:
            - "@request_stack"
            - "@payum"
