sylius_grid:
    grids:
        hraph_sylius_paygreen_plugin_paygreen_shop:
            driver:
                name: doctrine/orm
                options:
                    class: 'expr:parameter("hraph_sylius_paygreen_plugin.model.paygreen_shop.class")'
            sorting:
                name: asc
            fields:
                internalId:
                    type: string
                    label: sylius.ui.id
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: ~
                activate:
                    type: twig
                    label: hraph_sylius_paygreen_plugin.ui.validated
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/yesNo.html.twig"
                validatedAt:
                    type: datetime
                    label: hraph_sylius_paygreen_plugin.ui.validated_at
                    options:
                        format: d-m-Y H:i
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [id, name]
                activate:
                    type: boolean
                    label: sylius.ui.enabled
            actions:
                item:
                    update:
                        type: update
