hraph_sylius_paygreen_plugin_paygreen_shop:
    resource: |
        alias: hraph_sylius_paygreen_plugin.paygreen_shop
        section: admin
        path: /paygreen/shop
        permission: true
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: hraph_sylius_paygreen_plugin_paygreen_shop
        vars:
            all:
                subheader: hraph_sylius_paygreen_plugin.ui.paygreen_shop
                index:
                    icon: 'universal access'
    type: sylius.resource
